### ISSUE TITLE
php-pm + redis.

### ISSUE THREAD

**Issue by ibrunotome** [hernandev/ask-hernandev#1]
Olá! Parabéns pela iniciativa.

Já testou o php-pm com o laravel, mais especificamente com redis e horizon? Tenho muitos processos no horizon e pensei em testar o pm, mas nos primeiros testes já vi vários erros com o redis, e nem sequer a versão disponibilizada via docker rodou (erro 500 com log apontando falha de conexão com o redis), mas essa última creio que só faltou configurar melhor o redis no docker com o exemplo que dão na documentação do php-pm.

Aliás, vejo pouco (quase nada) docs sobre o assunto, vi que ainda tem memory leaks então talvez seja ousadia investir tanto nele por enquanto, o que você sabe sobre?

**Comment by hernandev** [comment]
Ok, vamos lá.

- **REDIS em produção precisa ser em modo cluster. 3 +servers / sentinel**

- **REDIS single é pra desenvolvimento.**

Coisas que você pode fazer:
- **Production-ready:**
  Verificar se o REDIS está realmente de acordo com os guias de produção.
- **Reduzir um pouco o paralelismo**
  Afinal, as filas são feitas pra processarem em sequência, logo um numero grande de processos (a menos que tenha tentado dizer trabalhos pendentes) é algo meio fora do comum. Possível, mas meio fora.

Se tá com dúvida, faça os mesmos testes contra uma instância trial lá do compose.com que tem REDIS Cluster hospedado ou mesmo a Amazon (ElastiCache).

O problema pode estar relacionado a N fatores.

A medida que tu interagir, vamos tentar chegar ao fundo desse dilema.

Agora, vamos ao ponto final:

Coisas que o PHP-PM vai de fato resolver pra você:

- **SIM: Aumentar a performance de cada Request**
    Mas, se a performance em sí não é problema (do ponto de vista lentidão) uma boa configuração do OPCache é o primeiro passo, antes de pensar em um process manager. 

- **SIM: Restaurar automaticamente processos que caiam**
   Novamente, porém, o Horizon faz isso sozinho, inclusive balanceamento entre filas, de acordo com o configurado.

Então, não pule ainda em uma decisão, sem abordar os passos simples antes.

**Comment by ibrunotome** [comment]
Quanto ao redis + horizon + php-fpm não há erros, está tranquilo, só pensei em melhorar a velocidade para que um processo não espere muito tempo na fila, outra solução seria aumentar a memória RAM para levantar mais workers, but $$ não cai do céu rsrs.

Quanto as informações sobre o php-pm, valeu!

**Comment by hernandev** [comment]
@ibrunotome isso se containers distintos e/ou servers distintos, a menos que seu servidor tenha muitos núcleos, não faz sentido pois você está gerando concorrência em cima da fila, cujo objetivo, é eliminar a concorrência.

**Comment by ibrunotome** [comment]
@hernandev por exemplo, tenho uma máquina de 3gb com 50 processos no horizon, as vezes chegam +-300 jobs de uma só vez e ela vai começar a processar 50, então 250 ficaram na fila esperando. Quis dizer que se eu aumento a memória ram, posso aumentar esses 50 processos disponíveis no horizon para que a espera diminua, porém antes de apelar para o hardware estava analisando outras maneiras de fazer isso.
